InventoryRegister/InventoryRegister/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('search/', include('haystack.urls')),
]

InventoryRegister/main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import index, issues, editIssues, deleteIssue, export_csv,\
    export_pdf, export_excel, register_page, login_page, logoutUser, userPage
from django.contrib.auth import views as auth_views
from main import forms
from django.contrib.auth import login

app_name = 'main'

urlpatterns = [
    path('', index, name='home'),
    path('issues/', issues, name='issues'),
    path('edit_issues/<int:issue_id>/', editIssues, name='edit_issues'),
    path('delete/<int:issue_id>/', deleteIssue, name='delete'),
    path('export_csv/', export_csv, name='export_csv'),
    path('export_pdf/', export_pdf, name='export_pdf'),
    path('export_excel/', export_excel, name='export_excel'),
    path('user/', userPage, name='user-page'),
    path('register/', register_page, name='register', ),
    path('login/', login_page, name='login'),
    path('logout/', logoutUser, name='logout'),
]

InventoryRegister/main/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.contrib.auth.models import (
    AbstractUser,
    BaseUserManager,
)


# Create your models here.

class OtherUsers(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=150, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name


class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class EquipmentIssue(models.Model):
    name = models.CharField(max_length=48)
    department = models.CharField(max_length=48)
    equipment_category = models.CharField(max_length=48)
    serial_number = models.CharField(max_length=48)
    description = models.TextField(blank=True)
    date_of_issue = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    is_issued = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    objects = ActiveManager()
    CATEGORIES = ('name', 'department', 'equipment_category', 'status, slug')

    def __str__(self):
        return self.name

    def save(self):
        self.slug = slugify(self.name)
        super(EquipmentIssue, self).save()

    def get_absolute_url(self):
        return reverse('issues', args=[str(self.slug)])


class EquipmentIssueTag(models.Model):
    equipmentIssues = models.ManyToManyField(EquipmentIssue, blank=True)
    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

InventoryRegister/main/forms.py
from django import forms
from .models import EquipmentIssue
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class IssueForm(forms.ModelForm):
    class Meta:
        model = EquipmentIssue
        fields = '__all__'


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

InventoryRegister/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from .models import EquipmentIssue
from . import forms
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from django.http import FileResponse
import io

from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
from django.db.models import Q

from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import ListView
import datetime
import csv

from tempfile import TemporaryFile, NamedTemporaryFile
from django.template.loader import render_to_string
from django.db.models import Sum
import xlwt
import os

from haystack.query import SearchQuerySet

os.add_dll_directory(r"C:\Program Files\GTK3-Runtime Win64")
from weasyprint import HTML
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import unauthenticated_user, allowed_users, admin_only
from django.contrib.auth.models import Group


# Create your views here.
@unauthenticated_user
def register_page(request):
    form = forms.CreateUserForm()
    if request.method == 'POST':
        form = forms.CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data['username']
            group = Group.objects.get(name='ordinary')
            user.groups.add(group)
            messages.success(request, 'Account was created for ' + username)
            return redirect('main:login')
    else:
        form = forms.CreateUserForm()
    context = {'form': form}
    return render(request, 'register.html', context)


@unauthenticated_user
def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main:home')
        else:
            messages.info(request, 'Username OR password is incorrect')
    context = {}
    return render(request, 'login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('main:login')


@login_required(login_url='main:login')
@allowed_users(allowed_roles=['admin'])
def index(request):
    q = request.GET.get('q', None)
    items = ''
    equipment = EquipmentIssue.objects.all()
    if q == None == q == '':
        equipment = EquipmentIssue.objects.all()
    elif q != None:
        equipment = EquipmentIssue.objects.filter(Q(name__icontains=q)|
                                                  Q(department__icontains=q)|
                                                  Q(equipment_category__icontains=q)|
                                                  Q(slug__icontains=q))

    context = {'equipment': equipment}
    return render(request, 'index.html', context)


@login_required(login_url='main:login')
@allowed_users(allowed_roles=['ordinary'])
def userPage(request):
    gadgets = request.user.ordinary.equipment_set.all()
    print('GADGETS', gadgets)
    context = {'gadgets': gadgets}
    return render(request, 'user.html', context)


@login_required(login_url='main:login')
@allowed_users(allowed_roles=['admin'])
def issues(request):
    form = forms.IssueForm()
    if request.method == 'POST':
        form = forms.IssueForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:home'))
    else:
        form = forms.IssueForm()
    context = {'form': form}
    return render(request, 'issues.html', context)


@login_required(login_url='main:login')
@allowed_users(allowed_roles=['admin'])
def editIssues(request, issue_id):
    issue = EquipmentIssue.objects.get(id=issue_id)
    if request.method != 'POST':
        form = forms.IssueForm(instance=issue)
    else:
        form = forms.IssueForm(instance=issue, data=request.POST)
        if form.is_valid():
            updated = form.save(commit=False)
            updated.save()
            return HttpResponseRedirect(reverse('main:home'))
    context = {'issue': issue, 'form': form}
    return render(request, 'edit_issues.html', context)


@login_required(login_url='main:login')
@allowed_users(allowed_roles=['admin'])
def deleteIssue(request, issue_id):
    try:
        issue = EquipmentIssue.objects.get(id=issue_id)
        issue.delete()
        return HttpResponse('Record successfully deleted')
    except:
        return HttpResponse('Record doesn\'t exist')


@login_required(login_url='main:login')
@allowed_users(allowed_roles=['admin'])
def export_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="Equipment.csv"'
    writer = csv.writer(response)
    writer.writerow(['name', 'description', 'serial number', 'date of issue'])
    equipment = EquipmentIssue.objects.all()

    for equip in equipment:
        writer.writerow([equip.name, equip.description,
                         equip.serial_number, str(equip.date_of_issue)])
    return response


@login_required(login_url='main:login')
@allowed_users(allowed_roles=['admin'])
def export_pdf(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'inline; attachment; filename=Equipment.pdf'
    response['Content-Transfer-Encoding'] = 'binary'

    equipment = EquipmentIssue.objects.filter(active=True)
    html_to_string = render_to_string('pdf_output.html', {'equipment': equipment})
    html = HTML(string=html_to_string)
    result = html.write_pdf()
    with open('tempo.bin', 'w+b') as output:
        output.write(result)
        output.flush()
        output = open(output.name, mode='rb', buffering=-1, closefd=True)
        response.write(output.read())
    return response


@login_required(login_url='main:login')
@allowed_users(allowed_roles=['admin'])
def export_excel(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename=equipment.xls'
    work_book = xlwt.Workbook(encoding='utf-8')
    work_sheet = work_book.add_sheet('equipment')
    row_num = 0
    font_style = xlwt.XFStyle()
    font_style.font.bold = True
    columns = ['DATE ISSUED', 'RECIPIENT NAME', 'RECIPIENT  DEPARTMENT',
               'EQPT CATEGORY', 'EQPT DESCRIPTION', 'EQPT SERIAL NUMBER',
               'EQPT STATUS', ]
    for col_num in range(len(columns)):
        work_sheet.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()
    rows = EquipmentIssue.objects.filter(active=True).values_list(
        'date_of_issue',
        'name', 'department', 'equipment_category', 'description', 'serial_number', 'status')

    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            work_sheet.write(row_num, col_num, str(row[col_num]), font_style)
    work_book.save(response)
    return response

InventoryRegister/main/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title> Air Zimbabwe IT Equipment Management System</title>
    <style>
         body,
		 html {
			margin: 0;
			padding: 0;
			height: 100%;
			/**background: #87ceeb !important;*/
		}
        #hello-msg {
            font-size: 18px;
            color: #fff;
            margin-right: 20px;

        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-dark"
     style="margin: 0 auto; width:100%; position:fixed; top:0px; z-index:100">
        <a class="navbar-brand" href="/"><i style="font-size:24px "><b></b></i></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class='nav-item {% if request.path == "/" %}active{% endif %}'>
                    <a class="nav-link" href="/"><button class="btn btn-sm btn-primary" style="background-color:green">Home</button></a>
                </li>
               <!-- <li class='nav-item {% if request.path == "/about-us/" %}active{% endif %}'>
                    <a class="nav-link"  href="/about-us/">About us</a>
                </li>-->
                {% if request.user.is_staff%}
                <li class='nav-item {% if request.path == "/contact-us/" %}active{% endif %}'>
                    <a  class="nav-link" href="/issues/"><button class="btn btn-sm btn-info" >New issue</button></a>
                    <a class="nav-link"  href="/contact-us/"></a>
                </li>
                <!--
                <li class="nav-item">
                    <a class="nav-link" href="/export_excel/"><button class="btn btn-sm btn-secondary">excel report</button></a>

                </li>
                -->
                <!--
                <li class="nav-item">
                    <a class="nav-link" href="/export_csv/"><button class="btn btn-secondary">csv report</button></a>

                </li>
                -->
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:export_pdf' %}"><button class="btn btn-sm btn-info">pdf report</button></a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/admin/"><button class="btn btn-sm btn-info" style="background-color:purple">Dashboard</button></a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="/register/"><button class="btn btn-sm btn-info" style="background-color:purple">Register</button></a>
                </li>
                {% endif %}
                {% if not request.user.is_authenticated %}
                 <li class="nav-item">
                    <a class="nav-link" href="/login/"><button class="btn btn-sm btn-info" style="background-color:purple">Login</button></a>
                </li>
                {% endif %}
                <li>
                    <form action="/" method="get" class="form-inline mt-2 mt-md-0">
                        <input id="q" name="q" value="{{ request.GET.q|capfirst }}" class="form-control mr-sm-2" type="text" placeholder="Search..." aria-label="Search">
                        <button class="btn btn-outline-success fa fa-search my-2 my-sm-0" type="submit" style=""></button>
                     </form>
                </li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                 </li>
                 <li class="nav-item">
                    <button id="hello-msg" class="btn btn-sm btn-info"><a  href="/logout/">Welcome, {{request.user}} Logout</a></button>
                </li>
            </ul>
        </div>
        <br />
        <br />

        <div>

        </div>
    </nav>
    <br />
{% block content %}
{% endblock %}
<br>
<footer class="webintern-footer" style="background-color:gray; color:#fff; position:scroll; bottom:0px; width:100%">
<div class="simple-text dark padding-sm" style="margin: 0 auto; width:100; z-index:100%; font-size:16px;">
<p>
    This is system is for Air Zimbabwe  Information Technology Department Inventory Management purposes only. And is only for authorised users.
    Kindly note that,  only authorised users can access this system. Your compliance is valued. Thank you.
</p>
</div>
<!--
<div class="simple-text last dark ">
<p>Get latest updates and offers.</p>
</div>
-->
<div class="tt-copy">
<div class="container">
<div class="row">
<div class="col-sm-6">
<div class="tt-copy-left">Copyright &copy; AirZim 2022. All rights reserved. </div>
</div>
<div class="col-sm-6">
<div class="tt-copy-right">
Created by: Tinodashe Kayenie &copy; superlight Intelligence Technologies
</div>
</div>
</div>
</div>
</div>
</footer>
</body>
</html>

InventoryRegister/main/templates/edit_issues.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
 {%block header %}
    <h2 style="text-align:center">Edit Issue Record</h2>
{% endblock header %}
<form method="post" style="width:95%; margin: 0 auto" >
   {% csrf_token %}
    {% bootstrap_form form %}
    <button name="submit" class="btn btn-primary" style="width:100%; margin: 0 auto">PRESS BUTTON TO UPDATE</button>
</form>
{% endblock %}

InventoryRegister/main/templates/index.html
{% extends 'base.html' %}
     {% block content %}
        {% block header %}
            <style>
        th{

        }
        th, td {
            text-align: left;
            padding: 8px;
        }
        tr:nth-child(even) {
            background-color: green;
        }
        </style>
    {% endblock header %}
    <h2 style="text-align:center;">Air Zimbabwe IT Equipment Management System</h2>
 <div class="row">
     <div class="col-md">
         <div class="card card-body">
    <table id="users" class="table table-striped table-bordered table-hover" style="margin: 0 auto; width:95%;">
        <thead style="color: #fff; background-color: #20b2aa;">
        <tr>
            <th>Entry Number</th>
             <th>Date Of Issue</th>
             <th>Recipient</th>
             <th>Department</th>
             <th>Category</th>
             <th>Description</th>
             <th>Serial Number</th>
             <th>Status</th>
             <th>Update Record</th>
             <th>Delete Record</th>
        </tr>
        </thead>
        <tbody>
        {% for qpt in equipment %}

            <tr>
                <td class="table-data" scope="row">{{ forloop.counter }}</td>
                <td >{{qpt.date_of_issue|date:"M d Y" }}</td>
                <td class="active">{{qpt.name}}</td>
                <td>{{qpt.department}}</td>
                <td>{{qpt.equipment_category}}</td>
                <td>{{qpt.description}}</td>
                <td>{{qpt.serial_number}}</td>
                <td>{{qpt.status}}</td>
                <td><a class="btn btn-sm btn-info" href="{% url 'main:edit_issues' qpt.id %}" style="color:#fff">update <i class="glyphicon !important" style="font-size:16px">&#x270f;</i></a> </td>
                <td class="danger"><a class="btn btn-sm btn-danger" href="{% url 'main:delete' qpt.id %}" style="color:#000"><i class="fa fa-trash-o" style="text-color:red; font-size:24px"><!--&#xf014;--></i></a> </td>
            </tr>
        {% endfor %}
        </tbody>

    </table>
         </div>
         </div>
    </div>
{% endblock %}

InventoryRegister/main/templates/issues.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
  <h2 style="text-align:center;">Issue Equipment</h2>
  <form method="post" style="margin: 0 auto; width:95%">
     {% csrf_token %}
     {% bootstrap_form form %}
      <button name="submit" class="btn btn-primary" style="margin: 0 auto; width:100%">PRESS TO ISSUE</button>
  </form>
{% endblock %}

InventoryRegister/main/templates/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

			}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username" class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							<input type="password" name="password" placeholder="Password" class="form-control">
						</div>
				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Login">
				   		</div>
					</form>
				</div>
				{% for message in messages%}
					<p id="messages">{{message}}</p>
				{% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'main:register' %}" class="ml-2">Sign Up</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		//form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

InventoryRegister/main/templates/pdf_output.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PDF Output</title>
    <style>
        @page{
            size: "A4";
            margin: 2.5cm 1.5cm 3.5cm 1.5cm;
          @top-center{
                content: "Air Zimbabwe IT Equipment Report";
            }
            @bottom-right{
                 content: "Page " counter(page) " of " counter(pages);
             }

        }
    </style>
    <hr>
</head>
<body>
    <h2>Issues Table</h2>

    <table class="table">
        <thead class="thead">
            <tr>
               <th>Entry Number</th>
                 <th>Date Of Issue</th>
                 <th>Recipient </th>
                 <th>Department</th>
                 <th>Category</th>
                 <th>Description</th>
                 <th>Serial Number</th>
                 <th>Status</th>
            </tr>

        </thead>

        <tbody>
        {% for qpt in equipment %}

            <tr>
                <th>{{ forloop.counter }}</th>
                <td>{{qpt.date_of_issue|date:"M d Y"}}</td>
                <td>{{qpt.name}}</td>
                <td>{{qpt.department}}</td>
                <td>{{qpt.equipment_category}}</td>
                <td>{{qpt.description}}</td>
                <td>{{qpt.serial_number}}</td>
                <td>{{qpt.status}}</td>

            </tr>
        {% endfor %}
        </tbody>

    </table>
</body>
</html>

InventoryRegister/main/templates/product-search.html
<!DOCTYPE html>
<html>
<head>
    <title>Django Search</title>
</head>
<body>

<form action="{% url 'main:search' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="name">
    <input type="submit" name="submit" value="Search">
</form>
{% for result in results %}
    {% if result %}
    <p>{{result.name}}</p>
    <p>{{result.department}}</p>
    {% else %}
     <p>No match for your search!</p>
    {% endif %}
{% endfor %}

</body>
</html>

InventoryRegister/main/templates/register.html
<!DOCTYPE html>
<html>

<head>
	<title>Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							 {{ form.username }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							 {{ form.email }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							 {{ form.password1 }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password2 }}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
					{{ form.errors }}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'main:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

InventoryRegister/main/templates/user.html
{% block content %}
{% include '' %}
<h3>User Profile</h3>
{% endblock %}